### ISSUE TITLE
Measurement problem under Python 3.9.0rc1

### ISSUE THREAD

**Issue by qwarkys** [coddingtonbear/python-myfitnesspal#107]
Myfitnesspal 1.14 crashes under 3.9.0rc1:

from measurement.measures import Energy, Weight, Volume
ImportError: cannot import name 'Weight' from 'measurement.measures' (C:\program files\python39\lib\site-packages\measurement\measures\__init__.py)

It installed cleanly (pip install myfitnesspal) once I installed the Windows binary for lxml.

1.16.1 won't install - crashing on measurements:
Collecting measurement<4.0,>=3.2.0
  Using cached measurement-3.2.0.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\program files\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\rdp\\AppData\\Local\\Temp\\pip-install-xra2nbag\\measurement\\setup.py'"'"'; __file__='"'"'C:\\Users\\rdp\\AppData\\Local\\Temp\\pip-install-xra2nbag\\measurement\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\rdp\AppData\Local\Temp\pip-pip-egg-info-6gtvn7iq'

1.15 installs, but crashes with: 
ImportError: cannot import name 'gcd' from 'fractions' (C:\program files\python39\lib\fractions.py)

**Comment by coddingtonbear** [comment]
Hey there @qwarkys -- thanks for the bug report! 

I hate to do this, but I'm afraid that's actually a problem in a dependency -- [`python-measurement`](https://github.com/coddingtonbear/python-measurement); it looks like that particular library is relying upon a feature that has maybe been moved in Python 3.9 and the folks who maintain that library these days would surely love to know about this bug, but unfortunately there's nothing to be done in `python-myfitnesspal` for fixing this for you.

What I'd recommend is opening a bug report on python-measurement (linked above) and they'll sort it out for you.

Cheers!
