### ISSUE TITLE
Are there rate-limits we should be aware of?

### ISSUE THREAD

**Issue by stopachka** [coddingtonbear/python-myfitnesspal#120]
Hey team! Excellent library -- it worked like magic! 

I was thinking of running a cron job that ran every hour, importing a bunch of data for me and my friends. This would hit MFP about ~100x / hour. I am a bit worried that this could trigger their rate limits / get my account blocked. I was wondering: is anyone aware of "limits" to scraping that MFP imposes?

**Comment by coddingtonbear** [comment]
I'm afraid nobody here works for MFP, so the best answer you might get here is "I don't know".  You could, though, possibly reach out to MFP themselves to see if they have abuse limits for their web UI?  That's where this library gets its data.  Good luck.
