### ISSUE TITLE
can't even download the repository 

### ISSUE THREAD

**Issue by AdrianReichert** [coddingtonbear/python-myfitnesspal#125]
I tried both ways, with pip and cloning from Github, pip did not work at all, but i got to install something with Github. But it is apparently not enough because most of the downloads failed. Any Ideas?

**Comment by hannahburkhardt** [comment]
Seems to be working for me using pip - can you post your command and output?

**Comment by coddingtonbear** [comment]
I'm going to close this issue since I haven't heard anything recently; if you're still having trouble, though @AdrianReichert, definitely feel free to reply.
