### ISSUE TITLE
How to get my daily kcal goal?

### ISSUE THREAD

**Issue by spamz23** [coddingtonbear/python-myfitnesspal#130]
Is this info available?

**Comment by hannahburkhardt** [comment]
It should be in the day object. Try:
```python
import myfitnesspal

client = myfitnesspal.Client('my_username')

day = client.get_date(2013, 3, 2)
day.goals
```

**Comment by coddingtonbear** [comment]
I believe @hannahburkhardt 's answer here will get you to what you need, @spamz23; so I'm going to close this.  Let us know if you're still stuck, though.
