### ISSUE TITLE
Support for sending and reading user messages

### ISSUE THREAD

**Issue by AgeOfMarcus** [coddingtonbear/python-myfitnesspal#131]

**Comment by coddingtonbear** [comment]
Hey there, @AgeOfMarcus !  I bet a lot of people would like that; definitely feel free to start a discussion in the "Discussions" tab at the top to see if you might be able to find somebody to collaborate with you on a Pull Request adding something like that. For the moment, though, I'm going to be closing this issue so I can keep the issue list limited to actual bugs and projects that are ongoing.

Cheers!
