### ISSUE TITLE
Enable to access account: list index out of range

### ISSUE THREAD

**Issue by llarbodiere** [coddingtonbear/python-myfitnesspal#133]
Hello,

When I try to follow the documentation to access my account I get the following error `list index out of range`, either if I save my password or pass it as an agrument.
I really want to use this library but it seems I cannot connect. 

Thanks,
Lucas

**Comment by hannahburkhardt** [comment]
I believe this is the login error that was fixed recently. Check your version and make sure you’re on 1.16.6. You can specify that specific version: `pip install myfitnesspal==1.16.6`

**Comment by llarbodiere** [comment]
Oh yes it works thanks a lot !
