### ISSUE TITLE
get_report - 'Client' object has no attribute 'get_report'

### ISSUE THREAD

**Issue by lukasz18dg** [coddingtonbear/python-myfitnesspal#141]
I tried to get all data from reports in MFP.
My code:

```
import datetime    
import myfitnesspal
client = myfitnesspal.Client('my_login', password="my_password")

thisweek = datetime.date(2022, 4, 11)
lastweek = datetime.date(2022, 4, 4)

client.get_report("Net Calories", "Nutrition")

above code will be finished with error:

```
`
AttributeError: 'Client' object has no attribute 'get_report'
`

Based on documentation: => https://python-myfitnesspal.readthedocs.io/en/latest/how_to/reports.html seems my code should working

**Comment by coddingtonbear** [comment]
I'm afraid that isn't quite yet released -- the PR for that was merged just a few days ago.  If you check out the `master` branch, though, you should find what you're looking for there.

I imagine I'll find the time to do another release, though, within a couple weeks.

Good luck!
