### ISSUE TITLE
BUG: Negative values export as positive

### ISSUE THREAD

**Issue by judgewooden** [coddingtonbear/python-myfitnesspal#142]
Some entries have negative values, like calories adjusted. 

Fix required in ```client.py```:

in ```def _get_numeric()```
change ```str_value = re.sub(r"[^\d.]+", "", string)```
to ```str_value = re.sub(r"[^-\d.]+", "", string)```

**Comment by hannahburkhardt** [comment]
Thanks for the catch! Could you open a pull request for this change?

**Comment by judgewooden** [comment]
okay: https://github.com/coddingtonbear/python-myfitnesspal/pull/143

**Comment by hannahburkhardt** [comment]
Fixed by #143
