### ISSUE TITLE
Authentication Error - Cookies

### ISSUE THREAD

**Issue by SaarthShah** [coddingtonbear/python-myfitnesspal#148]
Hi, I am getting this error while running myfitnesspal.client()

"MyfitnesspalLoginError: Could not access MyFitnessPal using the cookies provided by your browser.  Are you sure you have logged in to MyFitnessPal using a browser on this computer?"

I am already logged into myfitnesspal on two different browsers, and this still doesn't seem to work. Can you help me with what I can do to make sure my cookies are visible to the package on both my machine and a google colab notebook.

**Comment by hannahburkhardt** [comment]
Try specifying the browser. For example:
```
import myfitnesspal
import browser_cookie3

client = myfitnesspal.Client(browser_cookie3.chrome())
```

**Comment by SaarthShah** [comment]
> Try specifying the browser. For example:
> 
> ```
> import myfitnesspal
> import browser_cookie3
> 
> client = myfitnesspal.Client(browser_cookie3.chrome())
> ```

This did not work for me, unfortunately. I am trying to use browser_cookie3 and browser_cookie3.load() does not seem to contain the myfitnesspal cookies. However, when I import the regular browsercookie module, it seems to have the myfitnesspal cookies.

**Comment by SaarthShah** [comment]
Got it to work, thanks a lot!

**Comment by stefan-ber** [comment]
Helped me to let my code run as well - thx a lot !
