### ISSUE TITLE
brand_name sometimes lacks values

### ISSUE THREAD

**Issue by crueter** [coddingtonbear/python-myfitnesspal#181]
Sometimes, the brand_name field is a blank string when getting search results. This appears to be pretty common, but sometimes the brand field is populated for a whole search.

**Comment by hannahburkhardt** [comment]
Are you using `get_food_item_details`? If so, are you sure that the items you're looking at should have something other than a blank string for brand_name?

**Comment by crueter** [comment]
> Are you using `get_food_item_details`? If so, are you sure that the items you're looking at should have something other than a blank string for brand_name?

The particular search I noticed this on had a bunch of MFP Generic items which appear to have no brand_name field at all. Replacing blank strings with "Generic" matches up well with what MyFitnessPal searches look like.
