### ISSUE TITLE
facebook login

### ISSUE THREAD

**Issue by ellisonch** [coddingtonbear/python-myfitnesspal#31]
I use facebook to login to myfitnesspal.  As such, my account doesn't have a password, nor can I add one without disconnecting from facebook.

Is there/can there be a way to use python-myfitnesspal with facebook logins?

**Comment by coddingtonbear** [comment]
I'm afraid you can't log-in with your Facebook account directly from this library (for reasons that might be clear given that we can't open up a browser window in the library from which you can confirm to Facebook that you'd like to approve the login), but although it might not be obvious, you do always have a non-facebook MyFitnessPal username, and can always set a password.

If you check out your profile page by clicking on your username in the page header where it says "Hi <you>", you'll see your real username in the URL (and, I think, on the page itself), and you can set a password from your [account settings page](http://www.myfitnesspal.com/account/settings).

**Comment by coddingtonbear** [comment]
Let me know if this doesn't get you onto the right track, @ellisonch!

**Comment by ellisonch** [comment]
FWIW, if you authenticate using facebook, you can't seem to add a password.  If you go to the "set a password" page, it just says "Your account is authenticated through Facebook. Please disconnect to create a password."

Perhaps disconnecting, adding a password, and reconnecting might work.

At any rate, thanks anyway.
