### ISSUE TITLE
Quick Add

### ISSUE THREAD

**Issue by madhavajay** [coddingtonbear/python-myfitnesspal#33]
Hi,
I just had a quick play around with adding a Quick Add method to the API.
I get a 202 though, which is weird and it doesn't add the data to the website.
Wondering if anyone had any experience with this?

The code is pretty rough at the moment so not really ready for a pull request, but I could dump it in a GIST if someone might have an idea on why it doesn't work.

I guess they must be doing something extra with the previous requests when trying to "quick add".

**Comment by coddingtonbear** [comment]
No experience with this specifically, I'm afraid!  If you post your code in a gist, I could maybe help you troubleshoot, though.  Also -- I'm often on the [gitter channel](https://gitter.im/coddingtonbear/python-myfitnesspal) if you wanted to chat!
