### ISSUE TITLE
Extra white space in 'totals' and 'goals'

### ISSUE THREAD

**Issue by agbrook** [coddingtonbear/python-myfitnesspal#34]
There seems to have been a change on the myfitnesspal.com side that is adding \n<whitespace>calories<whitespace>\n' to at least the goals and totals results. I was able to fix it locally by changing the following function in client.py:

def _get_full_name(self, raw_name):
        name = raw_name.lower()**.strip()**
        if name not in self.ABBREVIATIONS:
            return name
        return self.ABBREVIATIONS[name]

I didn't want to go through creating a pull request for 8 characters, but thought it might be something that you could use.

**Comment by coddingtonbear** [comment]
Thanks for the bug report!  I'm curious about why you're resisting posting a pull request for this -- it'd help lots of people, and it might be a few days before I get a chance to circle back and have a look at this.  I promise -- it's easier than it sounds if you have already cloned the repo and made the changes!

**Comment by agbrook** [comment]
My reasoning is that I hadn’t already cloned the repo. I made the changes directly in site-packages/myfitnesspal. Mostly just laziness. I can go through the process though, if its going to be a little while for you. I haven’t nothing against it.

Andy Brook
Sr. Systems Administrator | Center for Research Informatics | University of Chicago
T: 773-834-0458 | http://cri.uchicago.edu

**Comment by coddingtonbear** [comment]
Thanks for the PR, sir!
