### ISSUE TITLE
Exercise Data

### ISSUE THREAD

**Issue by rafalio** [coddingtonbear/python-myfitnesspal#40]
Had a cursory look at the code and I'm not sure if this library has this feature.
Can I pull exercise data with this? If not you know any other good libraries for this?

**Comment by coddingtonbear** [comment]
I'm afraid this library doesn't provide that feature, no, and I'm not aware of any libraries providing that.  That being said, you're welcome to try adding it!  Feel free to hop onto [the gitter channel](https://gitter.im/coddingtonbear/python-myfitnesspal?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you want to chat about how to get started!

Cheers!
