### ISSUE TITLE
Is it possible to get steps data (synced from my iOS client)?

### ISSUE THREAD

**Issue by johnofcamas** [coddingtonbear/python-myfitnesspal#53]
I'm using the new 'get_exercise' api, but I don't see steps data in there.  Is it stored some other place?

**Comment by mtthwsar** [comment]
I think it might be in get_measurements, and you'll need to check what the measurement is called under http://www.myfitnesspal.com/measurements/check_in

**Comment by javiergarza** [comment]
No, steps are not listed under measurements. Anybody knows where to pull the API definition file? (swagger/RAML)

**Comment by coddingtonbear** [comment]
I'm afraid there is no publicly documented API-- what this library does is a combination of scraping the site's HTML and using undocumented APIs that one can see being used by the frontend.

**Comment by coddingtonbear** [comment]
Given that this issue has been open for quite a while with no positive answer, I'm going to guess that the answer is "No".  If somebody does find a way of pulling-in that data; I'd love to see a pull request adding it, though!

Cheers!

**Comment by mtthwsar** [comment]
Steps **ARE** listed under measurements for Fitbit (as "Fitbit steps") but I haven't seen them listed for Apple Watch or other trackers like Polar or Garmin.
