### ISSUE TITLE
dietary fiber in day.totals

### ISSUE THREAD

**Issue by vonavy15** [coddingtonbear/python-myfitnesspal#67]
Currently Day.totals returns a dict with keys Calories, carbs, fat, protein, sodium and sugar - which are availiable on https://www.myfitnesspal.com/food/diary/  page. 
There are other fields myfitnesspal stores, like vitamin A, vitamin D, potassium, Dietary Fiber and others, which would be helpful to analyze, especially fiber intake in my opinion. 
Any chance we could include it? Maybe by using  data export premium feature?

**Comment by coddingtonbear** [comment]
Could theoretically be possible using the premium features, but unfortunately this library relies entirely on what is directly displayed in the page.  If you do find a way of fetching that data programmatically, feel free to reach out to me about how that sort of functionality might be incorporated in a way that might work for folks both with and without premium access, and I can give you tips on what a pull request for such a feature might entail.

Cheers!
