### ISSUE TITLE
[Feature] Ability to search for food items and get food items' details

### ISSUE THREAD

**Issue by pydolan** [coddingtonbear/python-myfitnesspal#73]
This is a feature request to add the following two features: (1) ability to search for food items and get matching results, and (2) ability to get a particular item's details (nutrition info, servings, etc).

**Comment by coddingtonbear** [comment]
Those both sound like great ideas!  If you were to file a pull request adding those features, I'd be glad to work with you toward merging that feature in.  I'm afraid that Github issue boards aren't so great for managing feature requests, though, so I'm going to close this, but feel free to chat with me (and, potentially others) on the gitter channel about putting together such a feature as a PR.

Cheers!

**Comment by pydolan** [comment]
Thanks, PR coming shortly. Figured having an Issue would be useful, so feel free to re-open after PR comes in, or just leave closed -- whatever's easiest for you.  Will jump on Glitter once PR up.
