### ISSUE TITLE
Client._get_numeric returns 0 if string doesn't contain 'st' or 'lb' units

### ISSUE THREAD

**Issue by gg** [coddingtonbear/python-myfitnesspal#76]
The [recent commit](https://github.com/coddingtonbear/python-myfitnesspal/commit/d539e19c58e3c5d7391462f3f7e5656554bf41e7) for #30 introduced a bug: [`_get_numeric`](https://github.com/coddingtonbear/python-myfitnesspal/commit/d539e19c58e3c5d7391462f3f7e5656554bf41e7#diff-fcc062f0ce6fe9afce218a0bfa86daadR222) returns `0` if the string doesn't contain 'st' or 'lb' units (e.g. `_get_numeric('120')` returns `0`).

This occurs because the [`BRITISH_UNIT_MATCHER` regex](https://github.com/coddingtonbear/python-myfitnesspal/commit/d539e19c58e3c5d7391462f3f7e5656554bf41e7#diff-fcc062f0ce6fe9afce218a0bfa86daadR25) matches *any* string.

One way to fix this is to change the regex to only match strings that contain 'st':

```
(?:(?P<st>\d+) st)\W*(?:(?P<lbs>\d+) lb)?
```

You can test the regex here: https://regex101.com/r/HbAEZi/1

**Comment by coddingtonbear** [comment]
Whoops; good call.

**Comment by coddingtonbear** [comment]
Fixed as part of 1.13.3!
