### ISSUE TITLE
Add exercise to documentation

### ISSUE THREAD

**Issue by nathanmerrill** [coddingtonbear/python-myfitnesspal#79]
Looks like exercises was added recently.  I'm struggling to figure out how to use it, so some documentation would be great!

**Comment by AleenaCodes** [comment]
Same here, although when I run `day.exercises` it just returns `[<Cardiovascular>, <Strength Training>]` as opposed to any actual data, so I wonder if the exercise bit doesn't actually work!

**Comment by coddingtonbear** [comment]
I'm afraid that was a community contribution from @samhinshaw, so we'll either have to ask him to write some docs, or you folks can come together to try to write them -- I'd be glad to accept a PR covering that functionality's use.

Looking at [the code](https://github.com/coddingtonbear/python-myfitnesspal/blob/master/myfitnesspal/exercise.py#L18) it looks like each of the objects you see printed (`<Cardiovascular>` or `<Strength>`) has a couple useful properties:

* `name` ('cardiovascular' or 'strength', at least)
* `entries`
* `get_as_list()`

Try those out to see what you get!

**Comment by AleenaCodes** [comment]
Thanks @coddingtonbear ,  just tried it, and both `entries` and `get_as_list()` gave me what I wanted (name, duration and calories)

**Comment by coddingtonbear** [comment]
Could I trouble you too post some sample output from each of those commands so even somebody who doesn't use this feature of MFP might be able to write some docs?

**Comment by AleenaCodes** [comment]
No problem, I've submitted a [pull request](https://github.com/coddingtonbear/python-myfitnesspal/pull/82)

**Comment by coddingtonbear** [comment]
Thanks so much for adding some docs, @AleenaCodes; I'm sure that'll help lots of folks!

**Comment by samhinshaw** [comment]
Awesome, thanks @AleenaCodes! Sorry about that 😶
