### ISSUE TITLE
Unable to set authentication

### ISSUE THREAD

**Issue by pete7863** [coddingtonbear/python-myfitnesspal#84]
I just finished installing the package using 'pip install myfitnesspal', but I am unable to store my password for authentication using 'myfitnesspal store-password my_username'. After I enter that command, I get ''. -bash: myfitnesspal: command not found'. Is there something else I need to install or do? Any help is greatly appreciated!

**Comment by realPrimoh** [comment]
Having the same issue!

**Comment by TheTurtle42** [comment]
I'm in the same boat

**Comment by sidaga** [comment]
Has anyone found a solution?

**Comment by pete7863** [comment]
I believe the store-password is not functional on a raspberry pi (doesn't have a built-in password keychain). However, I ended up just using the raw credentials and storing them in a local json file. This seemed like a far easier option than looking for packages to support the password storing functionality.

**Comment by coddingtonbear** [comment]
I'm sure you've figured this out by now, @pete7863 , but it looks like when you installed `myfitnesspal`, the `myfitnesspal` binary wasn't added to your `$PATH`.  I can't tell you for certain where your local python installation will put binaries, but what you need to do is find that path (you could perhaps figure it out by running something like `find / -name 'myfitnesspal'`) and adding the directory in which you find the `myfitnesspal` executable to your `$PATH` list.

Cheers & good luck.
