### ISSUE TITLE
Feature request: Steps count

### ISSUE THREAD

**Issue by allthemore** [coddingtonbear/python-myfitnesspal#87]
Please add possibility to access daily steps count if steps were syncronized to mfp from other device.

**Comment by coddingtonbear** [comment]
Totally -- post a pull request adding this, and we can discuss it from there!  Like many small projects, you'd have to take on maintainership of that functionality, of course, given that the way we integrate with myfitnesspal is extremely brittle (relying almost entirely on UI scraping).

Good luck, and let me know if you need a hand with figuring out where to get started.

Cheers!

**Comment by allthemore** [comment]
It would be great if you could give me some hints on how to start working with this issue.

Thanks!
