### ISSUE TITLE
Question about your API application

### ISSUE THREAD

**Issue by hgducharme** [coddingtonbear/python-myfitnesspal#9]
Hi, sorry to open an irrelevant issue, but I had a question as to how long it took you to get approved for MFP's API? 

I just sent in my application yesterday, and I'm dyingggg to get approved.

**Comment by coddingtonbear** [comment]
Honestly, I'd like to know the answer to that question myself; I submitted my request a year and a half ago, and still have yet to hear anything.

That being said, the fact that their API is closed is why this library exists ;-).

**Comment by hgducharme** [comment]
Ohhh, my bad. I figured you were using your API key for this repo and others would be making calls off of it as well. I didn't realize it was scrapping data from MFP. 

Never mind then, looks like scrapping is the only way to go! 😞

**Comment by coddingtonbear** [comment]
Yeah, only scraping, I'm afraid :-/.   It isn't the most elegant solution in the world, but it seems to work just fine so far :-).

Cheers!
