### ISSUE TITLE
4 year old version of keyring?

### ISSUE THREAD

**Issue by hbmartin** [coddingtonbear/python-myfitnesspal#91]
mfp requires very old version of keyring (release April 2016), lots of compatibility issues with other packages.

**Comment by coddingtonbear** [comment]
This is a community-maintained project; as a member of that community, you can feel free to post a pull request upgrading that package if you can confirm that the API we are using is not affected by any API changes.

**Comment by hbmartin** [comment]
@coddingtonbear thanks for pointing this out! https://github.com/coddingtonbear/python-myfitnesspal/pull/92
