### ISSUE TITLE
No longer compatible with your measurements library

### ISSUE THREAD

**Issue by hillwithsmallfields** [coddingtonbear/python-myfitnesspal#97]
Hi, you changed "weight" to "mass" in your "measurements" library, and python-myfitnesspal won't load with the new version.

**Comment by coddingtonbear** [comment]
Ahh; at this point python-measurements is mostly maintained by people that aren't me, actually, so I didn't actually personally have a hand in that.  Would you mind posting a pull request either correcting that change in this library or alternatively update our `requirements.txt` such that it is pinned to a version before that change took place?

**Comment by hillwithsmallfields** [comment]
OK; I think I've hit another problem in the library, which actually looks familiar from when I used it before; I'll look at them both, and submit PRs.

**Comment by coddingtonbear** [comment]
I believe this issue was addressed via #98 ; thanks for posting a pull request!
