### ISSUE TITLE
Timestamp on food entries

### ISSUE THREAD

**Issue by JureSencar** [coddingtonbear/python-myfitnesspal#99]
Hi, would it be possible to obtain and expose timestamps on food Entries under Meal?

**Comment by coddingtonbear** [comment]
Maybe!  If it's exposed in the UI you see on the website, it's possible to update the library to ingest that information in some kind of useful way.  That said, we rely on contributors like you to add that kind of functionality -- if you'd like to make that possible, feel free to post a pull request and/or reach out on the gitter channel if you need a hand.

Cheers!
